const DIMENSIONS = {
  ROWS: 'ROWS',
  ALL_COLUMNS: 'ALL_COLUMNS',
};

const ALL_SHEETS = {
  SHEET_1: 'Sheet1',
  SHEET_2: 'Sheet2',
  DEV_TRIAL: 'DevTrial',
  BACKUP: 'BACKUP',
};

const REQUEST_METHODS = {
  POST: 'POST',
  PUT: 'PUT',
  PATCH: 'PATCH',
  GET: 'GET',
  DELETE: 'DELETE',
};

export { ALL_SHEETS, DIMENSIONS, REQUEST_METHODS };
