version: '3.3'

services:
  redis-commander:
    container_name: visaoswal-redis-commander
    hostname: redis-commander
    restart: always
    env_file: .env.production
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:${REDIS_HOST}:${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - target: 8081
        published: 8081
